Improvements in gradle build; Add metrics

diff --git a/movies/src/main/docker/Dockerfile.jvm b/movies/src/main/docker/Dockerfile.jvm
--- a/movies/src/main/docker/Dockerfile.jvm
+++ b/movies/src/main/docker/Dockerfile.jvm
@@ -1,9 +1,13 @@
 FROM gradle:7.0.2-jdk11 as BUILD
-COPY src /usr/src/app/src
+WORKDIR /usr/src/app
+# Only copy dependency-related files
 COPY settings.gradle.kts /usr/src/app
 COPY build.gradle.kts /usr/src/app
 COPY gradle.properties /usr/src/app
-WORKDIR /usr/src/app
+# Only download dependencies
+# Eat the expected build failure since no source code has been copied yet
+RUN gradle build > /dev/null 2>&1 || true
+COPY src /usr/src/app/src
 RUN gradle build -x test
 
 FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4 as RUN
